# Clé et nom du projet
sonar.projectKey=FrontEnd-GeoDom
#sonar.projectName=Backend - Piren-Seine

sonar.sources=src
sonar.tests=tests

sonar.javascript.lcov.reportPaths=./coverage/lcov.info

# URL et token
#sonar.host.url=${env.SONAR_HOST_URL}
#sonar.login=${env.SONAR_TOKEN}
