# Clé et nom du projet
sonar.projectKey=backend-piren-seine
#sonar.projectName=Backend - Piren-Seine

sonar.sources=.
sonar.tests=tests

sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=**/__init__.py, tests/**
sonar.tests.exclusions=**/__init__.py

# URL et token
#sonar.host.url=${env.SONAR_HOST_URL}
#sonar.login=${env.SONAR_TOKEN}
