[tox]
envlist = py310
skipsdist = True

[testenv]
setenv =
    DATABASE_PYNUTS_URL = {env:DATABASE_PYNUTS_URL}
    DATABASE_DONUTS_URL = {env:DATABASE_DONUTS_URL}
deps =
    -rrequirements.txt
commands =
    coverage run -m pytest --durations=0 tests/
    coverage xml

[coverage:run]
relative_files = True
source = .
branch = True
