[tox]
envlist = py313
skipsdist = True

[testenv]
setenv =
    DATABASE_PYNUTS_URL = {env:DATABASE_PYNUTS_URL}
    DATABASE_DONUTS_URL = {env:DATABASE_DONUTS_URL}
deps =
    -r requirements.txt
    pytest
    coverage
commands =
    coverage run --source=main.py --branch -m pytest --durations=0 tests/
    coverage xml -o coverage.xml

[coverage:run]
relative_files = True
source = main.py
branch = True

[coverage:report]
skip_covered = True
show_missing = True

