name: Pre-Prod Deploy to VPS

on:
  push:
    branches:
      - Pre-Production

jobs:
   frontend-tests:
     name: Frontend Tests
     runs-on: ubuntu-latest
     defaults:
       run:
         working-directory: FrontEnd
     steps:
       - uses: actions/checkout@v4
         with:
          fetch-depth: 0
       - name: Cache dependencies
         uses: actions/cache@v3
         with:
           path: ~/.npm
           key: ${{ runner.os }}-npm-cache
           restore-keys: |
             ${{ runner.os }}-npm-cache
       - name: Install Node.js
         uses: actions/setup-node@v4
         with:
           node-version: 'lts/*'
       - name: Install dependencies
         run: npm install
       - name: Run frontend tests with Vitest
         run: npm run test

   backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Backend
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: |
            ${{ runner.os }}-pip
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Remplacé 3.13 par 3.12 pour compatibilité
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Set environment variables
        run: |
          echo "DATABASE_PYNUTS_URL=${{ secrets.DATABASE_PYNUTS_URL }}" >> $GITHUB_ENV
          echo "DATABASE_DONUTS_URL=${{ secrets.DATABASE_DONUTS_URL }}" >> $GITHUB_ENV
          echo "LOG_LEVEL=${{ secrets.LOG_LEVEL }}" >> $GITHUB_ENV
          echo "TESTING=${{ secrets.TESTING }}" >> $GITHUB_ENV
      #- name: Run tests with pytest
      #  run: pytest tests/

   analyze-frontend:
     needs: frontend-tests
     name: Sonarqube Frontend
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
         with:
          fetch-depth: 0
       - name: Install dependencies
         working-directory: FrontEnd
         run: npm install
       - name: Run vitest for coverage
         working-directory: FrontEnd
         run: npm run coverage
       - name: Analyze Frontend with SonarQube
         uses: sonarsource/sonarqube-scan-action@v4
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONTEND }}
           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
         with:
           projectBaseDir: FrontEnd

   analyze-backend:
     needs: backend-tests
     name: Sonarqube Backend
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
         with:
          fetch-depth: 0
       - name: Setup Python
         uses: actions/setup-python@v5
         with:
          python-version: '3.12'
       - name: Install dependencies
         working-directory: Backend
         run: pip install -r requirements.txt
       - name: Set environment variables
         run: |
          echo "DATABASE_PYNUTS_URL=${{ secrets.DATABASE_PYNUTS_URL }}" >> $GITHUB_ENV
          echo "DATABASE_DONUTS_URL=${{ secrets.DATABASE_DONUTS_URL }}" >> $GITHUB_ENV
          echo "LOG_LEVEL=${{ secrets.LOG_LEVEL }}" >> $GITHUB_ENV
          echo "TESTING=${{ secrets.TESTING }}" >> $GITHUB_ENV
       - name: Analyze Backend with SonarQube
         uses: sonarsource/sonarqube-scan-action@v4
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACKEND }}
           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
         with:
           projectBaseDir: Backend

   deploy:
    name: Deploy to VPS
    needs:
     - analyze-backend
     - analyze-frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Build Frontend
        run: |
          cd FrontEnd
          npm install
          npm run build
      - name: Package Backend
        run: |
          cd Backend
          tar -czf back-end.tar.gz *
          mv back-end.tar.gz ../
      - name: Debug SSH Key
        run: |
          echo "${{ secrets.VPS_KEY }}" > debug_key
          chmod 600 debug_key
          ssh -i debug_key -o StrictHostKeyChecking=no piren_usr@lastproject.piren-seine.fr "echo 'SSH Connection Successful'"
      - name: Transfer build files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          source: "./*.tar.gz"
          target: "~/pre-production/"
          port: 22
          debug: true
      - name: Deploy on VPS
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          port: 22
          debug: true
          script: |
            cd ~/pre-production/
            bash deploy.sh