name: Push in Production

on:
  push:
    branches:
      - Production  
jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      new_tag: ${{ steps.get_tag.outputs.NEW_VERSION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: get_tag
        run: |
          LATEST_TAG=$(git tag --sort=-v:refname | head -n 1)
          echo "Latest tag: $LATEST_TAG"
          if [[ -z "$LATEST_TAG" ]]; then
            NEW_VERSION="v1.0.0"
          else
            NEW_VERSION=$(echo $LATEST_TAG | awk -F. '{print $1"."$2"."$3+1}')
          fi
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Create and push new tag
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git tag ${{ env.NEW_VERSION }}
          git push origin ${{ env.NEW_VERSION }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.NEW_VERSION }}
          name: "Release ${{ env.NEW_VERSION }}"
          body: "Automatic release of version ${{ env.NEW_VERSION }} 🎉"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy-to-vps:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy on VPS
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          port: 22
          debug: true
          script: |
            # Variables
            NEW_TAG="${{ needs.release.outputs.new_tag }}"  # Utilisation de l'output du job précédent
            DOWNLOAD_URL="https://github.com/${{ github.repository }}/archive/refs/tags/${NEW_TAG}.tar.gz"
            
            echo "🚀 Téléchargement de la release ${NEW_TAG} sur le VPS..."
            
            # Téléchargement de l'archive tar.gz directement sur le VPS
            wget --header="Authorization: token ${{ secrets.GITHUB_TOKEN }}" -O ~/production/geodom.tar.gz $DOWNLOAD_URL
            
            echo "🔧 Déploiement de la release sur le VPS..."
            script: |
            export DATABASE_PYNUTS_URL="${{ secrets.DATABASE_PYNUTS_URL }}"
            export DATABASE_DONUTS_URL="${{ secrets.DATABASE_DONUTS_URL }}"
            export SECRET_ADMIN_KEY="${{ secrets.SECRET_ADMIN_KEY }}"
            export ALGORITHM="${{ secrets.ALGORITHM }}" 
            bash deploy.sh production